# Generated by Django 3.0.2 on 2020-01-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpauth', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_key',
        ),
        migrations.AddField(
            model_name='otp',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OTP Generation Key'),
        ),
    ]
