# Generated by Django 3.0.2 on 2020-01-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpauth', '0003_user_latest_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
