# Generated by Django 3.0.2 on 2020-01-24 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('otpauth', '0005_auto_20200108_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='latest_otp',
        ),
        migrations.AddField(
            model_name='user',
            name='corporation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Corporation'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('A', 'Administrator'), ('T', 'Tourist'), ('O', 'Operator'), ('M', 'Manager')], default='T', max_length=1),
        ),
    ]
