# Generated by Django 3.0.2 on 2020-01-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpauth', '0006_auto_20200124_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
