# Generated by Django 3.0.2 on 2020-01-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otpauth', '0007_auto_20200124_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OTP Generation Key'),
        ),
    ]
