# Generated by Django 3.0.2 on 2020-01-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200124_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='available_through',
            field=models.DateTimeField(null=True),
        ),
    ]
