# Generated by Django 3.0.2 on 2020-01-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200124_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='available_through',
            field=models.DateTimeField(),
        ),
    ]
