# Generated by Django 3.0.2 on 2020-01-24 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200124_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='available_through',
            new_name='available_until',
        ),
    ]
