# Generated by Django 3.0.2 on 2020-01-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200124_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='available',
        ),
        migrations.RemoveField(
            model_name='order',
            name='available_until',
        ),
        migrations.AddField(
            model_name='trip',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='available_until',
            field=models.DateTimeField(null=True),
        ),
    ]
