# Generated by Django 3.0.2 on 2020-01-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200124_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='available_until',
            field=models.DateTimeField(),
        ),
    ]
