# Generated by Django 3.0.2 on 2020-01-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200124_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
